### ISSUE TITLE
UI updates from Alyssa

### ISSUE THREAD

**Issue by patudom** [cosmicds/tempo-lite#65]
<img width="784" alt="Screenshot 2024-10-17 at 2 31 07 PM" src="https://github.com/user-attachments/assets/73b7ab03-dcba-4079-98fe-f17425cd0998">

**Comment by Carifio24** [comment]
Just to add some context (since I was in the meeting where this image was put together):

* Changing the custom date to a calendar picker feels like an inevitable need anyway - a dropdown will get very unwieldy very fast.

* Alyssa felt that it wasn't clear that the progress bar is a progress bar, and also that it's unclear when all of the data is loaded (since the progress bar just disappears). The spinner idea feels to me like it would require too much vertical space to be easily readable, but what I suggested was that we put some text (say on the right) of the progress bar that's something like "Data loading: XX%". We could even keep the progress bar around once it's complete, fully filled with some text to indicate this, like "Data loaded!"

* For the other items, I think it's just the names of the headers. I know that Alyssa's general issue with the featured dates stuff is that there isn't any sort of indication before I click on a date of why I might care about it.

**Comment by patudom** [comment]
closing by #67
